<?xml version="1.0" encoding="utf-8"?><Database Name="FDA_CFS_CENTER" Class="Linq_CFSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.124;Initial Catalog=FDA_CFS_CENTER;Persist Security Info=True;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FDA_CFS_CENTERConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CER_DRUG_COUNTRY" Member="CER_DRUG_COUNTRies">
    <Type Name="CER_DRUG_COUNTRY">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_IDA_CER_NO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_IDA_COUNTRY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COUNTRY_NAME_ENG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CER_DRUG_IMPORT" Member="CER_DRUG_IMPORTs">
    <Type Name="CER_DRUG_IMPORT">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RCVNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RCVDATE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_DOWNLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_AUTHORIZE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_APPROVED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNSID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THANM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNTYPE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNNO_DISPLAY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ROAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THMBLNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AMPHRNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CHNGWTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_AGE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_NATION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_ROAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_THMBLNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_AMPHRNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_CHGWTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN_TEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CHECK_POINT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DRUG_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DRUG_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DRUG_MOO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DRUG_ROAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DRUG_THMBLNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DRUG_AMPHRNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DRUG_CHNGWTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REF_CODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="APPROVE_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="APPROVE_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NEWCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RGTNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RGTTPCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UNIT_CER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COMMENT_ADMIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DATE_APPROVED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DATE_EXP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DATE_PRINT_PAYMENT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PVNCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CER_TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WRITE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WRITE_AT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CER_DRUG_EDIT_ADDRESS" Member="CER_DRUG_EDIT_ADDRESSes">
    <Type Name="CER_DRUG_EDIT_ADDRESS">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_REGISTER_IDA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ENG_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ENG_ADDRESS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ENG_SOI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ENG_ROAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ENG_AMPRE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ENG_CHANGWAT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PHONE_NUMBER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ENG_THMBR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CER_DRUG_GENNO_MAX" Member="CER_DRUG_GENNO_MAXes">
    <Type Name="CER_DRUG_GENNO_MAX">
      <Column Name="IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GENNO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CER_DRUG_HEAD" Member="CER_DRUG_HEADs">
    <Type Name="CER_DRUG_HEAD">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RCVNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCVDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_UPLOAD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIZEN_DOWNLOAD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIZEN_AUTHORIZE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LCNSID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADDRESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_PROCESS_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="REF_CODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COMMENT_ADMIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COMMENT_BUSINESS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UNTIL_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CITIZEN_APPROVED" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IMPORT_TO_COUNTRY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TRADNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FORMULA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EXPORT_FROM_COUNTRY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="YN_STATUS_LICENSE_HOLDER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="REGISTER_NEWCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YN_SUMMARY_APPENDED" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YN_WITH_THE_LICENSE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YN_FROM_IS_PROCESS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YN_FROM_BEEN_INSPECTED" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YN_BY_ANOTHER_PARTY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="INPUT_IF_NO_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="YN_AUTHORIZATION_LACKING" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_I_II" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_I_III" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_IIA_IIII" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_IIA_V" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_IIB_II" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_IIB_III_I" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_III" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_III_I" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_III_II" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_III_III" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_V_IIII" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_V_IF_NO_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_YN_IIA_III" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_IIB_III_II" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_IIB_III_III" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_YN_IIB_III_IIII" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="XML_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YN_Health_Organization" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="INPUT_Applicant_for_certificate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="INPUT_Status_of_applicant" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="INPUT_name_and_address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UNIT_CER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="APPROVED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UTIL_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CPP_V_DOSAGE_FORM_ARE_2A31_1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_DOSAGE_FORM_ARE_2A31_2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_LICENSE_HOLDER_2A6_1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_LICENSE_HOLDER_2A6_2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_FOR_CERTIFICATE_2B1_1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_FOR_CERTIFICATE_2B1_2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_DOSAGE_FORM_ARE_2B21_1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_DOSAGE_FORM_ARE_2B21_2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_REMARKS_1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_V_REMARKS_2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TRANS_ATTRIBUTE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PRODUCT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COMPANY_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_I_NAME_IF_APPLICABLE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CPP_I_YN_EXPORT_COUNTRY_I_II" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPP_I_YN_EXPORT_COUNTRY_I_III" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LCNNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NAME_FOR_EXPORT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CER_TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DATE_PRINT_PAYMENT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RGTNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RGTTPCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PVNCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EACH_CONTAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EDIT_EACH_CONTAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REG_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="REG_DATE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="drgtpcd" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="pvnabbr" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="lpvncd" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CER_DRUG_LORPOR" Member="CER_DRUG_LORPORs">
    <Type Name="CER_DRUG_LORPOR">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RCVNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVDATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_DOWNLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_AUTHORIZE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_APPROVED" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNSID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DL_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DRUG_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PRODUCT_NO_BOTT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PRODUCT_NO_BOTT_LIQ" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PRODUCT_NO_BOX" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DATE_MFT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_EXP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_MFT_LIQ" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_EXP_LIQ" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_START" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_APPROVED" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_PRINT_PAYMENT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DESCRIPTION_DL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TOTAL_SUM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_SUM_UNIT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE_CER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCNTPCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNTYPE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PVNCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PVNABBR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCNNO_DISPLAY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REF_CODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PRODUCT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REG_NO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REG_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="THANM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_MFT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_MFT_LIQ" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COUNTRY_MFT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COUNTRY_MFT_LIQ" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="APPROVE_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="APPROVE_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NEWCODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RGTNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RGTTPCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UNIT_CER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COMMENT_ADMIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WRITE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WRITE_AT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CER_DRUG_NAME_EXPORT" Member="CER_DRUG_NAME_EXPORTs">
    <Type Name="CER_DRUG_NAME_EXPORT">
      <Column Name="pvncd" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="drgtpcd" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="rgttpcd" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="drgexp" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cntcd" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="rgtno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TEMPLATE_ATTACH" Member="TEMPLATE_ATTACHes">
    <Type Name="TEMPLATE_ATTACH">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LCNTPCD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATTACH_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATTACH_PIORITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ATTACH_FILE_EXTENSION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="conventpcd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GEN_RCV_NUMBER" Member="GEN_RCV_NUMBERs">
    <Type Name="GEN_RCV_NUMBER">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="YEAR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PVCODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LCNNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GENNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FORMAT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GROUP_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="REF_IDA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FILE_ATTACH" Member="FILE_ATTACHes">
    <Type Name="FILE_ATTACH">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME_FAKE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NAME_REAL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PATH" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EXTENSTION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LCNTPCD" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MAS_TEMPLATE_PROCESS" Member="MAS_TEMPLATE_PROCESSes">
    <Type Name="MAS_TEMPLATE_PROCESS">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCNTYPECD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GROUPS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PREVIEW" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PDF_TEMPLATE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_PATH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PDF_OUTPUT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MAS_PROCESS" Member="MAS_PROCESSes">
    <Type Name="MAS_PROCESS">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROCESS_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROCESS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PROCESS_DESCRIPTION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GROUP_CER" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>